### ISSUE TITLE
Mention Discord username of the faucet requester in the response output of the bot

### ISSUE THREAD

**Issue by CalinHumans** [0x4139/cosmos-discord-faucet#1]
Hi Vali,

Could you please have the faucet mention and tag the Discord:

Current output example at $request:
{
  "transaction": "238626FAA44DCFE5D3E2B6862A1E23B13EB35AB0873B28ABFEA94AACB8AB6C0A",
  "block": 48189,
  "gas": 91313
}

And modified should be something like this:

@Discord_username
{
  "transaction": "238626FAA44DCFE5D3E2B6862A1E23B13EB35AB0873B28ABFEA94AACB8AB6C0A",
  "block": 48189,
  "gas": 91313
}

Also, throttle message should look like:

@discord_username, you can request your uheart every 0.02 hours, please try again in 0.02 hours!

This is useful due to the fact that at some point, multiple users may request tokens in a short amount of time and there would be confusion in regards to which user does the transaction belong to

**Comment by 0x4139** [comment]
added in the last commit

**Comment by lightiv** [comment]
FYI, I am getting the following:

```
{
  "requester": "@undefined",
  "transaction": "02F61F34B117F59E06D5F39CF407116E559237A71642CF88D65AD3C93028CDE5",
  "block": 636002,
  "gas": 71897
}
```
Not it is returning **@undefined** instead of the actual requested.  I am not sure if this is an issue on my end or not.

**Comment by 0x4139** [comment]
You should retry with the latest docker image, this was just fixed, and check the environment variables of gas and amount for the fee.

**Comment by lightiv** [comment]
Hi yes, I created a script to delete all containers and images on start up of the faucet and now I see it is working perfectly for both fixes.  Greatly appreciated.
