### ISSUE TITLE
Problem Sending Token

### ISSUE THREAD

**Issue by lightiv** [0x4139/cosmos-discord-faucet#2]
When I request fund I get this error.  Where is the `2000uheart` defined or can I over-ride it for my token?  
```
Broadcasting transaction failed with code 13 (codespace: sdk). Log: got: 2000uheart required: 180ustake: insufficient fee
```
FYI, great work here.  This is the only Discord Faucet Bot I found on Discord I could get to work.  (Two days of trying to get the others to run.)

**Comment by lightiv** [comment]
Ok, found the reference in /util/api.js
```
    const result = await client.sendTokens(address.address, addr, [amount], {
      amount: [
        {
          denom: 'uheart',
          amount: '2000'
        }
      ],
      gas: '180000' // 180k
    })
    return result
  }
```
Should that be `for both the fees and gas` passed variable as opposed to hard coded?

**Comment by lightiv** [comment]
FYI, I made this hard code edit and it resolved the problem.

**Comment by 0x4139** [comment]
Yes, it seems i forgot to use the env variable, will push a fix later.

**Comment by 0x4139** [comment]
solved.
