### ISSUE TITLE
SSL Support for API/RPC Endpoints?

### ISSUE THREAD

**Issue by lightiv** [0x4139/cosmos-discord-faucet#5]
Can we get support for SSL endpoints?
```
RPC_ENDPOINT - Node RPC to use ex: http://your_node:26657
API_ENDPOINT - Node API to use ex: http://your_node:1317
```

**Comment by 0x4139** [comment]
I am actually using https endpoints and do not have any kind of issue, could you describe the issue you are having?

**Comment by 0x4139** [comment]
closed due to lack of information
